<?php
$id = $article->id ?? 0;
?>

<ul id="mdguide">
	<li>The <strong>page</strong> dropdown menu can be used to assign the article to another page</li>
	<li>Use the <strong>position</strong> menu to change the position on the page, input the <strong><em>absolute</em></strong> number you want the article to appear at.</li>
	<li>For largely stylistic purposes some articles belong together, this is achieved by having a token of "id.class" in the <strong>meta data</strong> field ie: "tvcoverage.section" (see below), moving these articles is not advised, rather move the non-section articles around the section block.</li>
	<li>The <strong>meta data</strong> field can be used to set an id and/or class on the article, not strictly a content management task, as it infers a knowledge of the <a href="https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model" target="_blank">DOM</a>, but - in consultation with your friendly web administrator - it can be used to apply some light styling, or as above communicate intent to <a href="https://www.itonlinelearning.com/blog/html-css-and-javascript-essential-front-end-languages-explained/">css/js</a>.
	Three options: a single word ie: <tt>"id"</tt>: applies a unique id; a
      single word that starts with a period ie:<tt>".class"</tt>: applies a
      single classname; two words separated by a period ie:<tt>"id.class"</tt>:
      applies both.
	</li>
	<li>The <strong>date</strong> field is required for new articles, the <strong>summary</strong> field is for internal use only and cannot be edited. The <strong>content</strong> field is where the real work is done, a rudimentary aquaintance with the Markdown language will prove beneficial and the links below helpful.</li>
	<li>
		<a href="https://www.markdownguide.org/getting-started/" target="_blank"><strong>The Markdown Guide</strong> by Matt Cone</a>
	</li>
	<li>The toolbar above provides some handy shortcuts for creating/deleting markdown markup. For a comprehensive guide click the link above. I would also encourage total newbies to complete this series of <a href="https://commonmark.org/help/tutorial/" target="_blank">interactive</a> lessons.</li>
	<li>For inline formatting: For a single word selection just place the cursor within the wo<mark>r</mark>d and click to apply the required formatting, otherwise start and end your selection anywhere within the fi<mark>rst and last wo</mark>rds.</li>
	<li>For <b>clearing</b> click first/last/only word or again straddle the formatted text before clicking the appropriate button.</li>

	<li>The <a href="#heading"><strong>H</strong></a> button will with each click add a hash to the start of the line, returning to one hash at the seventh succesive click, The result would be a heading from <strong>h1</strong> thru <strong>h6</strong>. Given that this provides precious little advantage over manually editing the hashes a little more utility is provided. Clicking in an empty line will automatically format the heading using the content of the <a href="#title"><strong>title</strong></a> field. If the title were missing hashes they will be restored, - default is h3 - the heading should also be formatted as a link for styling purposes, following this format ###[my heading](#), finally editing the title field will prompt you to accept the changes.</li>
	<li>The <a href="#bold"><strong>B</strong></a> button will toogle a double pair of asterisks on the selected text. For a single word simply place the cursor anywhwere in the word and click. The result would be to <strong>embolden</strong> the text. To use an actual asterisk use the HTML entity "&amp;ast;" eg **my footnote&amp;ast;**, for bold asterisk, or **my footnote**&amp;ast; for normal.</li>
	<li>The <a href="#ital"><em><strong>I</strong></em></a> button will toogle a single pair of asterisks on the selected text. For a single word see above. The result would be to <em>italicise</em> the text. Already <strong>emboldened</strong> text will be respected. Therefore <strong>my bold text</strong> would become <em><strong>my bold text</strong></em>.</li>
	<li>The <a href="#list"><strong>list</strong></a> button converts a <strong>selection</strong> of lines into an unordered list:
		<ol>
			<li>• a</li>
			<li>• b</li>
			<li>• c</li>
		</ol>
		Subsequent clicks will cycle between no list (paragraphs) and a list. With a list alternating between an ordered list and an unordered list.
	</li>
	<li>The <a href="#para"><strong>¶</strong></a> is a helper if you are brave enough to be editing on a mobile device.
		To embolden a particular string mid sentence, for instance, you would need to isolate it into its own paragraph before treble-clicking to select the entire new paragraph, then click the bold button. Clicking <strong>¶</strong> button will remove the line breaks you had to create. To create an actual paragraph add <strong>two</strong> returns before your target paragraph.</li>
	<li>
	<li>The <a href="#line" style="line-height: 0px;font-size:1.5em"><strong>•</strong></a> adds two spaces and a new line - Markdown to create a html break tag - before the previous sentence; place cursor in a sentence ending in a full stop (period) and click. That would hardly be taxing to do manually so further utility is provided by doing a global replace of <strong>selected</strong> text with the text provided in a window prompt.
	</li>
	<li>The <a href="#link"><strong>LINK</strong></a> button creates a link on the <strong>selected</strong> text. A confirm dialog window opens. Enter a genuine link to either an external website ("https://www.bbc.co.uk/") or an internal web page ("/enquiries/{#id}"), or to a resource (/resource/assets/{pagename}/my.pdf), as a bare minimum a hash (#) is required. To add a <strong><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes/title"  title="a link to information about the role of the title attribute">title</a></strong> to the link add <strong>one</strong> space after the hyperlink followed by the title content, but nested in double quotes. <!--(If you are wrapping an image and wish it to float LEFT prefix any title with a &lt; or with &gt; for RIGHT)--> By default all links will open in a separate browser window, courtesy of an attribute block of <a href="https://andycarter.dev/blog/the-difference-between-target-blank-and-target-blank" target="_blank">{target=_blank}</a>. Markdown <strong>reference-style</strong> links are created by default as they result in less clutter in the main content of the article. The label on new links created this way will be an integer [2]/[2]:. If preferred you can manually enter short descriptive text, ie [chukka]/[chukka]:, (no spaces!) just make sure that both parts of the reference link match. See <strong><a href="https://www.markdownguide.org/basic-syntax/#reference-style-links" target="_blank">here</a></strong> for further details.</li>
	<li>Finally reference links are listed at the bottom of the article in the order they appear in the copy, although this is not a requirement. To CLEAR the link, click anywhere within the <strong><em>link copy</em></strong> and click this button again.</li>
	<li>The <a href="#relink"><strong>RELINK</strong></a> button allows you to switch link styles converting reference style links to inline links (and vice versa) by clicking either in the <strong><em>label box</em></strong> for reference style links or anywhere within the <strong><em>actual hyperlink text</em></strong>. This will also work with <strong>linked</strong> images, place cursor within the path to the file.</li>
	<li>The <a href="#span"><strong>&lt;/&gt;</strong></a> sets/unsets any <a href="https://w3context.com/html/basic/html-inline-elements.jsp" target="_blank"><strong>legitimate inline html tag</strong></a> (excluding self-closing tags). It invokes a prompt button to allow you to type in the tag name, defaulting to span. It otherwise behaves as the bold/italic button. Make a selection to surround multiple words, or place the cursor in the target word for a single word. Click within the tag boundaries to remove. The same thing can obviously be achieved manually and in some cases you may wish to furnish the tag with a relevant attribute. Directly using HTML in Markdown applications does not have 100% support however, again <a href="https://www.markdownguide.org/getting-started/" target="_blank">see the guide </a> for details. Finally entering a <strong>!</strong> will surround the selected text with comment tags and the text will not be displayed. Select the commented text and click again to remove. The default tag will be a span but that can be manually edited.
	</li>
	<li>One further use is to use up to two valid web color names INSTEAD of a tag in the prompt dialog box to color a <b>span</b> of text. Inputting UPPERCASE letters will embolden the text. The optional second color will paint in a background color also.</li>
	<li>The <a href="#img"><strong>IMAGE</strong></a> button adds an INLINE image. OK, now, this would normally never be required as images are <strong><em>related to but not included in</em></strong> the article text. These images are managed by clicking the icons below the submit button of this form, but for the occasional <strong>icon/logo</strong> where it would be considered decorative content, this may prove useful. <a id="demo" href="#edit_link"><img alt="demo" src="<?= ASSETS . 'live/edit_img_alt.png' ?>"></a> All images must have an <strong><a href="https://en.wikipedia.org/wiki/Alt_attribute#:~:text=The%20alt%20attribute%20is%20the,is%20applied%20cannot%20be%20rendered." target="_blank">alt</a></strong> attribute even if it is an empty string. Clicking the button will prompt you to enter the alternate text. <strong><em>This will only work if you click in an empty line.</em></strong>
		After confirming a second dialog box will open. The <strong>full path directory</strong> to the file will be <strong>automatically provided</strong> just append the filename to it and an optional title, see link above. Inline images will be placed in their own paragraph and by default images use the markdown <a href="https://daringfireball.net/projects/markdown/syntax#:~:text=Span%20Elements-,Links,link%20text's%20closing%20square%20bracket." title="link to the website of John Gruber, co-creator of the Markdown markup language" target="_blank"><strong>inline link</strong></a> style to help differentiate them from standard hyperlinks. They will by default float left of the article text, to float right you need to add an <a href="https://michelf.ca/projects/php-markdown/extra/#spe-attr" target="_blank" title="link to instructions regarding extra attributes"><strong>attribute block</strong></a> immediately after the closing parantheses, like so <mark>(...){.right}</mark>  and do bear in mind that images will be rendered at the physical size of the uploaded file.</li><li>A way to constrain the size to the line-height of the article text is to wrap the image in a link. Select the <strong><em>alt text</em></strong>, click the <strong>link</strong> button and refer to the <a href="#link">link</a> instructions above. Any existing attribute block on the image will be copied to the link where it now needs to be. Finally an atttibute block containing <a href="#demo"><strong>".none"</strong></a> instead of ".right" or ".left" will render the image on its own line. You are also at liberty to copy the entire image construct [![alt]...] to the middle of an existing paragraph where it will display inline. The results may, leave something <a id="demo" class="none" href="#edit_link"><img alt="demo" src="<?= ASSETS . 'live/edit_img_alt.png' ?>"></a>to be desired and you may have to resort to utilising style attribute eg: {style=vertical-align:text-bottom} within the attribute; you would also be right in thinking that this is way too much information for what should be a relatively simple <strong>content</strong> management system. To automate this wrapping of an image with a link supply a title that begins with (or consists entirely of) <strong>two consecutive</strong> instances of the following characters:<strong> &lt;,&gt;,&ndash;</strong> to float, left, right or none. The link location defaults to # (an internal link).</li>
	<li>It should be noted that images deployed this way SHOULD NOT be tracked in the database, to achieve this enter a "!" at the beginning of the meta_data field in the upload form, the file will be copied to the <strong>full path directory</strong> above. A list of untracked files may be found <a href="/asset/getuntracked/<?= $id; ?>">here</a>.</li>
	<li>To <strong>remove</strong> the image place the cursor in the <strong><em>alt text</em></strong> and click the <strong>image</strong> button again. Don't forget you can always manually enter the link and title copy you require if preferred, again refer to the <a href="https://www.markdownguide.org/basic-syntax/#reference-style-links" target="_blank">guide</a> for further details.</li>
	</li>
	<li>The <a href="#revert"><strong>ARROW</strong></a> button CLEARS all edits, not yet submitted.</li>
	<li id="help">The <strong>?</strong> button toggles this guide. As will clicking on this line.</li>
</ul>